spring:
  application:
    name: store
stripe:
  apiUrl: https://api.stripe.com
  enabled: true
  timeout: 1000
  supported-currencies: USD,EUR,GBP
payment:
  service: paypal
user:
  id: 01
  email: test@gmail.com
  password: 123456
  name: John Mayhem
mail:
  host: admin@gmail.com
  port: 8080